@startuml
    actor Тренер
    actor Спрортсмен

    usecase "Додавати, видаляти, сортувати спортсменів в групі" as TUC1
    usecase "Редагування відвідування та успішності" as TUC2
    usecase "Створення профілю спрортсмена" as TUC3
    usecase "Система календаря" as TUC4

    usecase "Редагування особістом профілю" as SUC1
    usecase "Перегляд загальна даних особістої групи" as SUC2
    usecase "Перегляд календаря подій" as SUC3
    usecase "Перегляд особістої успішністі" as SUC4
    usecase "Перегляд тренерів" as SUC5

    Спрортсмен -|> Тренер
    Тренер ---> SUC1
    Тренер -> TUC1
    Тренер --> TUC2
    Тренер ---> TUC3
    Тренер ----> TUC4
    
    Спрортсмен -> SUC1
    Спрортсмен --> SUC2
    Спрортсмен ---> SUC3
    Спрортсмен ----> SUC4
    Спрортсмен -----> SUC5

@enduml