@startuml
    actor Тренер
    actor Спрортсмен
    
    usecase "Формирование пользователей" as TUC1
    usecase "Формирование групп" as TUC2
    usecase "Оценивание спрорсменов в группе" as TUC3
    usecase "Просмотр статистики" as TUC4
    usecase "Формирование под-групп" as TUC5
    usecase "Формирование раписания и программы для групп" as TUC6
    usecase "Формирования целей для групп" as TUC7
    
    usecase "Редактировать профиль" as SUC1
    usecase "Просматривать группы" as SUC2
    usecase "Просматировать статистику" as SUC3
    usecase "Просматривать расписание" as SUC4
    usecase "Просматривать учебную программу" as SUC5
    
    Спрортсмен -|> Тренер
    Тренер ---> SUC1
    Тренер -> TUC1
    Тренер --> TUC2
    Тренер ---> TUC3
    Тренер ----> TUC4
    Тренер -----> TUC5
    Тренер ------> TUC6
    Тренер -------> TUC7
    
    Спрортсмен -> SUC1
    Спрортсмен --> SUC2
    Спрортсмен ---> SUC3
    Спрортсмен ----> SUC4
    Спрортсмен -----> SUC5

@enduml