-- MySQL Script generated by MySQL Workbench
-- Sat Jan  9 20:36:59 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`User`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`User` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `Full Name` VARCHAR(200) NOT NULL,
  `Age` INT NOT NULL,
  `Level` TINYINT NOT NULL,
  `Weight` TINYINT NOT NULL,
  `Height` TINYINT UNSIGNED NOT NULL,
  `Trainer` TINYINT NOT NULL,
  `Marks` INT NOT NULL,
  `Password` VARCHAR(45) NOT NULL,
  `E-Mail` VARCHAR(45) NOT NULL,
  `Telephone` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Awards`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Awards` (
  `idUser` INT NOT NULL,
  `Description` TEXT(255) NULL,
  `Place` INT NULL,
  UNIQUE INDEX `idUser_UNIQUE` (`idUser` ASC),
  PRIMARY KEY (`idUser`),
  CONSTRAINT `fk_Awards_User1`
    FOREIGN KEY (`idUser`)
    REFERENCES `mydb`.`User` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Groups`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Groups` (
  `idGroup` INT NOT NULL,
  `Group Number` TEXT(20) NULL,
  `TokenTimetable` TEXT(200) NULL,
  PRIMARY KEY (`idGroup`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`UsersInGroup`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`UsersInGroup` (
  `id_group` INT NOT NULL,
  `id_user` INT NOT NULL,
  CONSTRAINT `fk_table1_User1`
    FOREIGN KEY (`id_user`)
    REFERENCES `mydb`.`User` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_table2_Groups1`
    FOREIGN KEY (`id_group`)
    REFERENCES `mydb`.`Groups` (`idGroup`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`News`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`News` (
  `idNews` INT NOT NULL,
  `Title` TEXT(100) NOT NULL,
  `Content` TEXT(5000) NOT NULL,
  `Author` VARCHAR(200) NULL,
  `DateCreated` DATE NOT NULL,
  `idGroup` INT NOT NULL,
  PRIMARY KEY (`idNews`),
  UNIQUE INDEX `idNews_UNIQUE` (`idNews` ASC),
  CONSTRAINT `fk_News_Groups1`
    FOREIGN KEY (`idGroup`)
    REFERENCES `mydb`.`Groups` (`idGroup`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `mydb`.`User`
-- -----------------------------------------------------
START TRANSACTION;
USE `mydb`;
INSERT INTO `mydb`.`User` (`id`, `Full Name`, `Age`, `Level`, `Weight`, `Height`, `Trainer`, `Marks`, `Password`, `E-Mail`, `Telephone`) VALUES (0, 'John Doe', 18, 1, 54, 190, 0, 15, 'test', 'info@localhost:8888', '123456789');

COMMIT;


-- -----------------------------------------------------
-- Data for table `mydb`.`Awards`
-- -----------------------------------------------------
START TRANSACTION;
USE `mydb`;
INSERT INTO `mydb`.`Awards` (`idUser`, `Description`, `Place`) VALUES (0, 'TEST', 1);

COMMIT;


-- -----------------------------------------------------
-- Data for table `mydb`.`Groups`
-- -----------------------------------------------------
START TRANSACTION;
USE `mydb`;
INSERT INTO `mydb`.`Groups` (`idGroup`, `Group Number`, `TokenTimetable`) VALUES (0, 'TEST #0', NULL);

COMMIT;


-- -----------------------------------------------------
-- Data for table `mydb`.`UsersInGroup`
-- -----------------------------------------------------
START TRANSACTION;
USE `mydb`;
INSERT INTO `mydb`.`UsersInGroup` (`id_group`, `id_user`) VALUES (0, 0);

COMMIT;

