@startuml
  |Тренер|
      start
      : Тренер вибирає групу і \n переходить до неї;
  |Система|
      : Повертає сторінку з групою;
  |Тренер|
      : Натискає на необхідний стовпець \n в з'явившейся таблиці;
 |Система|
     : Cортує таблицю по цій колонці \n  за зменшенням;
@enduml