@startuml
    |Тренер|
        start
        : Натискає на кнопку\n "Добавити спортсмена";
    |Система|
        : Повертає форму \n введення нового спортсмена;
    |Тренер|
        : Вводить дані спортсмена:\nФІО,\nE-Mail,\nТелефон,\nПояс,\nВік,\nВага,\nЗріст;
    |Система|
        : Генерує логін та пароль;
        : Зберігає зміни;
        : Відправляє на зазначену\n пошту дані для входу;
        : Повертає повідомлення\n про успішне виконання;
@enduml
