@startuml
    |Тренер|
        start
        : Натискає на кнопку\n "Створити групу";
    |Система|
        : Повертає форму\nстворення нової групи;
    |Тренер|
        : Вибирає зі списку\nспортсменів з позначкою\n"Без групи";
        : Дає назву групи;
        : Натискає на кнопку\n "Готово";
    |Система|
        : Зберігає зміни;
        : Повертає повідомлення\n про успішне виконання;
@enduml
