@startuml
   |Тренер|
       start
       : Переходить в свій профіль;
   |Система|
       : Повертає сторінку з профілем;
   |Тренер|
       : Натискає на кнопку "Редагувати";
  |Система|
      : Дає можливість змінювати всі поля;
  |Тренер|
       : Змінює необхідну інорфмацію;
       : Натискає на кнопку "Зберегти";
  |Система|
      : Зберігає всі зміни;

@enduml