@startuml
    |Тренер|
        start
        : Тренер открывает вкладку Каледанрь;
    |Система|
        : Повертає форму\nстворення нової групи;
    |Тренер|
        : Вибирає зі списку\nспортсменів з позначкою\n"Без групи";
        : Дає назву групи;
    |Система|
        : Зберігає зміни;
        : Повертає повідомлення\n про успішне виконання;
@enduml