@startuml
   | Спортсмен |
       start
       : Переходить в свій профіль;
   | Система |
       : Повертає сторінку з профілем;
   | Спортсмен |
       : Натискає на кнопку "Редагувати";
  | Система |
      : Дає можливість змінювати всі поля;
  | Спортсмен |
       : Змінює необхідну інорфмацію;
       : Натискає на кнопку "Зберегти";
  | Система |
      : Зберігає всі зміни;

@enduml