@startuml
   |Тренер|
       start
       : Переходити на сторінку "Спортсмени";
   |Система|
       : Повертає список спортсменів;
   |Тренер|
       : Переходити на сторінку спортсмена;
       : Натискає на кнопку "Редагувати";
  |Система|
      : Дає можливість змінювати всі поля;
  |Тренер|
       : Змінює необхідну інорфмацію;
       : Натискає на кнопку "Зберегти";
  |Система|
      : Зберігає всі зміни;
@enduml