@startuml
   |Тренер|
       start
       : Переходити на сторінку групу;
   |Система|
       : Повертає сторінку групу;
   |Тренер|
       : Виділяє спортсмена;
       : Натискає на кнопку "Видалити спортсмена";
   |Система|
      : Видаляє виділеного спортсмена з групи;
@enduml