@startuml
   |Тренер|
       start
       : Переходити на сторінку "Спортсмени";
   |Система|
       : Повертає список спортсменів;
   |Тренер|
       : Переходити на сторінку спортсмена;
       : Натискає "Видалити Спортсмена";
   |Система|
      : Видаляє спортсмена;
@enduml